/// An About dialog for the app.
///
// Time-stamp: <Monday 2024-07-08 09:20:05 +1000 Graham Williams>
///
/// Copyright (C) 2024, Software Innovation Institute, ANU.
///
/// Licensed under the GNU General Public License, Version 3 (the "License").
///
/// License: https://www.gnu.org/licenses/gpl-3.0.en.html.
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://www.gnu.org/licenses/>.
///
/// Authors: Kevin Wang, Graham Williams

library;

import 'package:flutter/material.dart';

import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:solidpod/solidpod.dart';

Future<void> aboutDialog(BuildContext context) async {
  final appInfo = await getAppNameVersion();

  if (context.mounted) {
    showAboutDialog(
      context: context,
      applicationLegalese: '© 2024 Software Innovation Institute ANU',
      applicationIcon: Image.asset(
        'assets/images/keypod_logo.png',
        width: 100,
        height: 100,
      ),
      applicationName: appInfo.name,
      applicationVersion: appInfo.version,
      children: [
        const SizedBox(
          // Limit the width of the about dialog box.

          width: 300,

          child: MarkdownBody(
            // Ensure we can slect any of the text, especially since we are
            // inside a [SelectableArea] as per hom.dart.

            selectable: true,

            data: '''
**A key-value pair manager.**

Key Pod is an app for managing your secure and private
key-value data in your Solid Pod. The key-value pairs
can store any kind of data, indexed by the key.

The app is written in Flutter and the open source code
is available from github at https://github.com/anusii/keypod.
You can try it out online at https://keypod.solidcommunity.au.

The concept for the app and images were generated by
large language models.

*Authors: Anuska Vidanage, Graham Williams, Jess Moore, Zheyuan Xu,
Kevin Wang, Ninad Bhat, Dawei Chen.*

''',
          ),
        ),
      ],
    );
  }
}
